spring.application.name=rag-system

# Provide your OpenAI API key here
spring.ai.openai.api-key=AIzaSyBBjyYRm3eTIYwwtGbFl2L5hGP-FHiIPjk
spring.ai.openai.chat.options.model=gpt-3.5-turbo

# Optional: Server port
server.port=8080
